// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
// See the LICENCE file in the repository root for full licence text.

using System;
using System.Collections.Generic;
using Humanizer;
using osu.Game.Rulesets.Catch.Difficulty;

namespace PerformanceCalculatorGUI.Configuration
{
    public static class CatchDifficultyTuningParameters
    {
        public static readonly IReadOnlyList<DifficultyTuningParameter<CatchDifficultyConstants>> All = new[]
        {
            doubleParam(nameof(CatchDifficultyConstants.FinalPPMultiplier), t => t.FinalPPMultiplier, (t, v) => t with { FinalPPMultiplier = v },
                minValue: 0.8, maxValue: 1.2),
            doubleParam(nameof(CatchDifficultyConstants.SrPostMultiplier), t =>  t.SrPostMultiplier, (t, v) => t with { SrPostMultiplier = v },
                minValue: 0.05, maxValue: 2.0),
            doubleParam(nameof(CatchDifficultyConstants.SrOffset), t =>  t.SrOffset, (t, v) => t with { SrOffset = v },
                minValue: 0.05, maxValue: 2.0),
            doubleParam(nameof(CatchDifficultyConstants.SrScalerY6), t =>  t.SrScalerY6, (t, v) => t with { SrScalerY6 = v }, minValue: 10.5, maxValue: 11.5),
            doubleParam(nameof(CatchDifficultyConstants.SrScalerY5), t =>  t.SrScalerY5, (t, v) => t with { SrScalerY5 = v }, minValue: 9.8, maxValue: 10.5),
            doubleParam(nameof(CatchDifficultyConstants.SrScalerY4), t =>  t.SrScalerY4, (t, v) => t with { SrScalerY4 = v }, minValue: 9.0, maxValue: 9.8),
            doubleParam(nameof(CatchDifficultyConstants.SrScalerY3), t =>  t.SrScalerY3, (t, v) => t with { SrScalerY3 = v }, minValue: 7.5, maxValue: 9.0),
            doubleParam(nameof(CatchDifficultyConstants.SrScalerY2), t =>  t.SrScalerY2, (t, v) => t with { SrScalerY2 = v }, minValue: 5.5, maxValue: 7.5),
            doubleParam(nameof(CatchDifficultyConstants.SrScalerY1), t =>  t.SrScalerY1, (t, v) => t with { SrScalerY1 = v }, minValue: 2.5, maxValue: 5.5),
            doubleParam(nameof(CatchDifficultyConstants.SrScalerY0), t =>  t.SrScalerY0, (t, v) => t with { SrScalerY0 = v }, minValue: 1.0, maxValue: 2.5),
            doubleParam(nameof(CatchDifficultyConstants.ApproachRateSecondConstant), t => t.ApproachRateSecondConstant, (t, v) => t with { ApproachRateSecondConstant = v },
                minValue: 0.30, maxValue: 0.50),
            doubleParam(nameof(CatchDifficultyConstants.BeginningTimePenaltyPower), t => t.BeginningTimePenaltyPower, (t, v) => t with { BeginningTimePenaltyPower = v },
                minValue: 0.10, maxValue: 0.50),
            doubleParam(nameof(CatchDifficultyConstants.BeginningFullPenalty), t => t.BeginningFullPenalty, (t, v) => t with { BeginningFullPenalty = v },
                minValue: 0.40, maxValue: 0.70),
            doubleParam(nameof(CatchDifficultyConstants.DefaultDecayWeight), t => t.DefaultDecayWeight, (t, v) => t with { DefaultDecayWeight = v },
                minValue: 0.8, maxValue: 1.0),
            doubleParam(nameof(CatchDifficultyConstants.LowSpeedThresholdLSR), t => t.LowSpeedThresholdLSR, (t, v) => t with { LowSpeedThresholdLSR = v },
                minValue: 6.0, maxValue: 12.0),
            doubleParam(nameof(CatchDifficultyConstants.UnaffectedPercantagePrecisionLSR), t => t.UnaffectedPercantagePrecisionLSR, (t, v) => t with { UnaffectedPercantagePrecisionLSR = v },
                minValue: 0.55, maxValue: 0.85),
            doubleParam(nameof(CatchDifficultyConstants.LocalStarRatingMaxConstant), t => t.LocalStarRatingMaxConstant, (t, v) => t with { LocalStarRatingMaxConstant = v },
                minValue: 0.80, maxValue: 2.50),
            doubleParam(nameof(CatchDifficultyConstants.LocalStarRatingMinConstant), t => t.LocalStarRatingMinConstant, (t, v) => t with { LocalStarRatingMinConstant = v },
                minValue: 0.20, maxValue: 1.40),
            doubleParam(nameof(CatchDifficultyConstants.LocalStarRatingCorrelationConstant), t => t.LocalStarRatingCorrelationConstant, (t, v) => t with { LocalStarRatingCorrelationConstant = v },
                minValue: 0.05, maxValue: 0.70),
            doubleParam(nameof(CatchDifficultyConstants.PerformanceLengthLinearPace), t => t.PerformanceLengthLinearPace, (t, v) => t with { PerformanceLengthLinearPace = v },
                minValue: 0.25, maxValue: 0.50),
            doubleParam(nameof(CatchDifficultyConstants.PerformanceLengthCutoff), t => t.PerformanceLengthCutoff, (t, v) => t with { PerformanceLengthCutoff = v },
                minValue: 1200, maxValue: 2200),
            doubleParam(nameof(CatchDifficultyConstants.PerformanceLengthLogarithmicPace), t => t.PerformanceLengthLogarithmicPace, (t, v) => t with { PerformanceLengthLogarithmicPace = v },
                minValue: 0.15, maxValue: 0.75),
            doubleParam(nameof(CatchDifficultyConstants.PerformanceValueMultiplier), t => t.PerformanceValueMultiplier, (t, v) => t with { PerformanceValueMultiplier = v },
                defaultEnabled: true, minValue: 1.040, maxValue: 1.120),
            doubleParam(nameof(CatchDifficultyConstants.PrecisionRawWeightHyperjumps), t => t.PrecisionRawWeightHyperjumps, (t, v) => t with { PrecisionRawWeightHyperjumps = v },
                minValue: 0.90, maxValue: 1.00),
            doubleParam(nameof(CatchDifficultyConstants.PrecisionRawWeightHyperjumpAfterJump), t => t.PrecisionRawWeightHyperjumpAfterJump, (t, v) => t with { PrecisionRawWeightHyperjumpAfterJump = v },
                minValue: 0.90, maxValue: 1.00),
            doubleParam(nameof(CatchDifficultyConstants.PrecisionRawWeightJumpAfterHyperjump), t => t.PrecisionRawWeightJumpAfterHyperjump, (t, v) => t with { PrecisionRawWeightJumpAfterHyperjump = v },
                minValue: 0.93, maxValue: 1.00),
            doubleParam(nameof(CatchDifficultyConstants.PrecisionRawWeightJumps), t => t.PrecisionRawWeightJumps, (t, v) => t with { PrecisionRawWeightJumps = v },
                minValue: 0.80, maxValue: 1.00),
            doubleParam(nameof(CatchDifficultyConstants.PrecisionDelayedWeight), t => t.PrecisionDelayedWeight, (t, v) => t with { PrecisionDelayedWeight = v },
                minValue: 0.60, maxValue: 1.00),
            doubleParam(nameof(CatchDifficultyConstants.PrecisionStrainAmplitude), t => t.PrecisionStrainAmplitude, (t, v) => t with { PrecisionStrainAmplitude = v },
                minValue: 20.0, maxValue: 120.0),
            doubleParam(nameof(CatchDifficultyConstants.PrecisionStrainShift), t => t.PrecisionStrainShift, (t, v) => t with { PrecisionStrainShift = v },
                minValue: -30.0, maxValue: 30.0),
            doubleParam(nameof(CatchDifficultyConstants.PrecisionStrainPace), t => t.PrecisionStrainPace, (t, v) => t with { PrecisionStrainPace = v },
                minValue: 10.0, maxValue: 40.0),
            doubleParam(nameof(CatchDifficultyConstants.PrecisionStrainMultiplier), t => t.PrecisionStrainMultiplier, (t, v) => t with { PrecisionStrainMultiplier = v },
                minValue: 15.0, maxValue: 85.0),
            doubleParam(nameof(CatchDifficultyConstants.HighPrecisionThreshold), t => t.HighPrecisionThreshold, (t, v) => t with { HighPrecisionThreshold = v },
                minValue: -25.0, maxValue: 35.0),
            doubleParam(nameof(CatchDifficultyConstants.HighPrecisionPace), t => t.HighPrecisionPace, (t, v) => t with { HighPrecisionPace = v },
                minValue: 2.5, maxValue: 3.5),
            doubleParam(nameof(CatchDifficultyConstants.HighPrecisionPower), t => t.HighPrecisionPower, (t, v) => t with { HighPrecisionPower = v },
                minValue: 1.0, maxValue: 2.0),
            doubleParam(nameof(CatchDifficultyConstants.MaxPrecisionCorrection), t => t.MaxPrecisionCorrection, (t, v) => t with { MaxPrecisionCorrection = v },
                minValue: 1.15, maxValue: 1.40),
            doubleParam(nameof(CatchDifficultyConstants.SpeedSnapAmplitude), t => t.SpeedSnapAmplitude, (t, v) => t with { SpeedSnapAmplitude = v },
                minValue: 1.0, maxValue: 45.0),
            doubleParam(nameof(CatchDifficultyConstants.SpeedSnapShift), t => t.SpeedSnapShift, (t, v) => t with { SpeedSnapShift = v },
                minValue: -75.0, maxValue: 30.0),
            doubleParam(nameof(CatchDifficultyConstants.SpeedSnapPace), t => t.SpeedSnapPace, (t, v) => t with { SpeedSnapPace = v },
                minValue: 20.0, maxValue: 80.0),
            doubleParam(nameof(CatchDifficultyConstants.SpeedSnapMultiplier), t => t.SpeedSnapMultiplier, (t, v) => t with { SpeedSnapMultiplier = v },
                minValue: 0.75, maxValue: 1.75),
            doubleParam(nameof(CatchDifficultyConstants.SpeedBurstAmplitude), t => t.SpeedBurstAmplitude, (t, v) => t with { SpeedBurstAmplitude = v },
                minValue: 1.0, maxValue: 45.0),
            doubleParam(nameof(CatchDifficultyConstants.SpeedBurstShift), t => t.SpeedBurstShift, (t, v) => t with { SpeedBurstShift = v },
                minValue: -75.0, maxValue: 30.0),
            doubleParam(nameof(CatchDifficultyConstants.SpeedBurstPace), t => t.SpeedBurstPace, (t, v) => t with { SpeedBurstPace = v },
                minValue: 20.0, maxValue: 80.0),
            doubleParam(nameof(CatchDifficultyConstants.SpeedBurstMultiplier), t => t.SpeedBurstMultiplier, (t, v) => t with { SpeedBurstMultiplier = v },
                minValue: 0.75, maxValue: 1.75),
            doubleParam(nameof(CatchDifficultyConstants.SpeedConsistencyAmplitude), t => t.SpeedConsistencyAmplitude, (t, v) => t with { SpeedConsistencyAmplitude = v },
                minValue: 1.0, maxValue: 45.0),
            doubleParam(nameof(CatchDifficultyConstants.SpeedConsistencyShift), t => t.SpeedConsistencyShift, (t, v) => t with { SpeedConsistencyShift = v },
                minValue: -75.0, maxValue: 30.0),
            doubleParam(nameof(CatchDifficultyConstants.SpeedConsistencyPace), t => t.SpeedConsistencyPace, (t, v) => t with { SpeedConsistencyPace = v },
                minValue: 20.0, maxValue: 80.0),
            doubleParam(nameof(CatchDifficultyConstants.SpeedConsistencyMultiplier), t => t.SpeedConsistencyMultiplier, (t, v) => t with { SpeedConsistencyMultiplier = v },
                minValue: 0.75, maxValue: 1.75),
            doubleParam(nameof(CatchDifficultyConstants.ReadingHighCsPower), t => t.ReadingHighCsPower, (t, v) => t with { ReadingHighCsPower = v },
                minValue: 1.3, maxValue: 1.9),
            doubleParam(nameof(CatchDifficultyConstants.ReadingHighCsRate), t => t.ReadingHighCsRate, (t, v) => t with { ReadingHighCsRate = v },
                minValue: 0.30, maxValue: 0.50),
            doubleParam(nameof(CatchDifficultyConstants.ReadingHighCsPenaltyHypers), t => t.ReadingHighCsPenaltyHypers, (t, v) => t with { ReadingHighCsPenaltyHypers = v },
                minValue: 0.6, maxValue: 0.9),
            doubleParam(nameof(CatchDifficultyConstants.ReadingLocalRhythmPenalty), t => t.ReadingLocalRhythmPenalty, (t, v) => t with { ReadingLocalRhythmPenalty = v },
                minValue: 0.91, maxValue: 0.98),
            doubleParam(nameof(CatchDifficultyConstants.ReadingExplicitRhythmPenalty), t => t.ReadingExplicitRhythmPenalty, (t, v) => t with { ReadingExplicitRhythmPenalty = v },
                minValue: 0.90, maxValue: 1.00),
            doubleParam(nameof(CatchDifficultyConstants.ReadingImplicitRhythmPenalty), t => t.ReadingImplicitRhythmPenalty, (t, v) => t with { ReadingImplicitRhythmPenalty = v },
                minValue: 0.95, maxValue: 1.00),
            doubleParam(nameof(CatchDifficultyConstants.ReadingSimilarDistancePenalty), t => t.ReadingSimilarDistancePenalty, (t, v) => t with { ReadingSimilarDistancePenalty = v },
                minValue: 0.80, maxValue: 0.95),
            doubleParam(nameof(CatchDifficultyConstants.ReadingAlternatingDistancePenalty), t => t.ReadingAlternatingDistancePenalty, (t, v) => t with { ReadingAlternatingDistancePenalty = v },
                minValue: 0.95, maxValue: 1.00),
            doubleParam(nameof(CatchDifficultyConstants.ReadingHyperchainPenalty), t => t.ReadingHyperchainPenalty, (t, v) => t with { ReadingHyperchainPenalty = v },
                minValue: 0.88, maxValue: 1.00),
            doubleParam(nameof(CatchDifficultyConstants.ReadingNonHyperchainPenalty), t => t.ReadingNonHyperchainPenalty, (t, v) => t with { ReadingNonHyperchainPenalty = v },
                minValue: 0.91, maxValue: 1.00),
            doubleParam(nameof(CatchDifficultyConstants.ReadingHighVelocityNerf), t => t.ReadingHighVelocityNerf, (t, v) => t with { ReadingHighVelocityNerf = v },
                minValue: 0.02, maxValue: 0.25),
            doubleParam(nameof(CatchDifficultyConstants.ReadingHighDistanceBuff), t => t.ReadingHighDistanceBuff, (t, v) => t with { ReadingHighDistanceBuff = v },
                minValue: 0.01, maxValue: 0.50),
            doubleParam(nameof(CatchDifficultyConstants.ReadingHighDistancePower), t => t.ReadingHighDistancePower, (t, v) => t with { ReadingHighDistancePower = v },
                minValue: 1.0, maxValue: 1.8),
            doubleParam(nameof(CatchDifficultyConstants.ReadingFuturePrecisionBuff), t => t.ReadingFuturePrecisionBuff, (t, v) => t with { ReadingFuturePrecisionBuff = v },
                minValue: 0.05, maxValue: 0.25),
            doubleParam(nameof(CatchDifficultyConstants.StandingWidthAdditiveConstant), t => t.StandingWidthAdditiveConstant, (t, v) => t with { StandingWidthAdditiveConstant = v },
                minValue: 1.20, maxValue: 1.30),
            doubleParam(nameof(CatchDifficultyConstants.PrecisionCorrectionDistanceExponent), t => t.PrecisionCorrectionDistanceExponent, (t, v) => t with { PrecisionCorrectionDistanceExponent = v },
                minValue: 0.60, maxValue: 1.10),
            doubleParam(nameof(CatchDifficultyConstants.PrecisionCorrectionTimeExponent), t => t.PrecisionCorrectionTimeExponent, (t, v) => t with { PrecisionCorrectionTimeExponent = v },
                minValue: 0.60, maxValue: 1.60),
            doubleParam(nameof(CatchDifficultyConstants.PrecisionCorrectionDistanceWeight), t => t.PrecisionCorrectionDistanceWeight, (t, v) => t with { PrecisionCorrectionDistanceWeight = v },
                minValue: 0.10, maxValue: 0.90),
            doubleParam(nameof(CatchDifficultyConstants.DoubleTimeNerf), t =>  t.DoubleTimeNerf, (t, v) => t with { DoubleTimeNerf = v },
                minValue: 0.0, maxValue: 1.0),
        };

        private static DifficultyTuningParameter<CatchDifficultyConstants> doubleParam(string propertyName, Func<CatchDifficultyConstants, double> getter,
                                                                                       Func<CatchDifficultyConstants, double, CatchDifficultyConstants> setter,
                                                                                       bool defaultEnabled = true, double minValue = 0.01, double? maxValue = null)
        {
            string label = propertyName.Humanize();
            return DifficultyTuningParameter<CatchDifficultyConstants>.ForDouble(label, label, getter, setter, defaultEnabled, minValue, maxValue);
        }

        private static DifficultyTuningParameter<CatchDifficultyConstants> intParam(string propertyName, Func<CatchDifficultyConstants, int> getter,
                                                                                    Func<CatchDifficultyConstants, int, CatchDifficultyConstants> setter,
                                                                                    bool defaultEnabled = true, int minValue = 1, int? maxValue = null)
        {
            string label = propertyName.Humanize();
            return DifficultyTuningParameter<CatchDifficultyConstants>.ForInt(label, label, getter, setter, defaultEnabled, minValue, maxValue);
        }
    }
}
